# Generated by Django 5.0.6 on 2024-07-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='feture_image',
            new_name='feature_image',
        ),
    ]
